apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ws001-api
spec:
  host: ws001-api
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: blue
      labels:
        version: blue
    - name: green
      labels:
        version: green
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ws002-pingpong
spec:
  host: ws002-pingpong
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: blue
      labels:
        version: blue
    - name: green
      labels:
        version: green
