# ws001-api
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ws001-api
spec:
  hosts:
    - "*"
  gateways:
    - api-gateway
  http:
    # 路由規則
    - match:
        - uri:
            regex: .*\/(private|public)\/api\/.*
      route:
        - destination:
            host: ws001-api
            port:
              number: 7001
            subset: blue
          weight: 100
        - destination:
            host: ws001-api
            port:
              number: 7001
            subset: green
          weight: 0
      # CORS
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PUT
          - DELETE
        allowCredentials: true
        allowHeaders:
          - "*"

---
# ws002-pingpong
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ws002-pingpong
spec:
  hosts:
    - ws002-pingpong
  http:
    - route:
        # 金絲雀部署: 調整流量請 kubectl edit , 勿更新此檔
        - destination:
            host: ws002-pingpong
            subset: blue
          weight: 100
        - destination:
            host: ws002-pingpong
            subset: green
          weight: 0
---
# ws003-auth
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ws003-auth
spec:
  hosts:
    - ws003-auth
  http:
    - route:
        # 金絲雀部署: 調整流量請 kubectl edit , 勿更新此檔
        - destination:
            host: ws003-auth
            subset: blue
          weight: 100
        - destination:
            host: ws003-auth
            subset: green
          weight: 0
