# http 路由規則
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: http-path
spec:
  hosts:
    # 和 010-Gateway 裡的 hosts 同步
    - "ares.workshop.com"
    - "sit.ares.workshop.com"
    - "prod.ares.workshop.com"
  gateways:
    - api-gateway
  http:
    ## ws001-api
    - match:
        - uri:
            regex: .*\/(private|public)\/api\/.*
      route:
        - destination:
            host: ws001-api
            port:
              number: 7001
            subset: blue
          weight: 100
        - destination:
            host: ws001-api
            port:
              number: 7001
            subset: green
          weight: 0
      # CORS
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PUT
          - DELETE
        allowCredentials: true
        allowHeaders:
          - "*"

    # ws002-pingpong
    - match:
        - uri:
            regex: .*\/(private|public)\/pingpong\/.*
      route:
        # 金絲雀部署: 調整流量請 kubectl edit , 勿更新此檔
        - destination:
            host: ws002-pingpong
            subset: blue
            port:
              number: 8002
          weight: 100
        - destination:
            host: ws002-pingpong
            port:
              number: 8002
            subset: green
          weight: 0

---
# ws002-pingpong
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ws002-pingpong
spec:
  hosts:
    # svc name
    - ws002-pingpong
  http:
    - route:
        # gRPC
        - destination:
            host: ws002-pingpong
            subset: blue
            port:
              number: 7002
          weight: 100
        - destination:
            host: ws002-pingpong
            port:
              number: 7002
            subset: green
          weight: 0
