# Depends 030-auth-filter
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: accesslog-filter
  namespace: ares
spec:
  workloadSelector:
    labels:
      app: ws001-api
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value: # lua filter specification
          name: envoy.lua
          config:
            inlineCode: |-
              function envoy_on_request(request_handle)

                request_handle:logCritical("v2")
                local headers = request_handle:headers()

                -- request headers
                local path = headers:get(":path")
                local method = headers:get(":method")
                local xff = headers:get("x-forwarded-for")
                local xsecret = headers:get("x-secret")
                local requestId = headers:get("x-request-id")

                -- request body
                local requestBody = ""
                if (request_handle:body()~=nil) then
                  requestBody = request_handle:body():getBytes(0, request_handle:body():length())
                end

                -- 塞進 context 給 response
                request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "path", path)
                request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "method", method)
                request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "xff", xff)
                request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "xsecret", xsecret)
                request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "requestId", requestId)
                request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "requestBody", requestBody)

              end
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value: # lua filter specification
          name: envoy.lua
          config:
            inlineCode: |-
              function envoy_on_response(response_handle)

                local status = response_handle:headers():get(":status")
                local context = response_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.lua")

                path = context["path"]
                method = context["method"]
                xff = context["xff"]
                xsecret = context["xsecret"]
                requestId = context["requestId"]
                requestBody = context["requestBody"]

                if (xsecret == nil) then xsecret = "" end
                if (xff == nil) then xff = "" end

                requestBody = string.gsub(requestBody,"\"","\\\"")
                xsecret = string.gsub(xsecret,"\"","\\\"")

                jsonPaylog = "{\"logName\": \"ACCESS_LOG_FILTER\",\"status\":"..status..",\"path\":\""..path.."\",\"method\":\""..method.."\",\"xff\":\""..xff.."\",\"requestBody\":\""..requestBody.."\",\"xsecret\":\""..xsecret.."\",\"requestId\":\""..requestId.."\"}"
                print(jsonPaylog)

                -- response 戴上 x-request-id
                response_handle:headers():add("X-Request-ID", requestId)


              end